#!/bin/sh
# to run this script: 
#   - make sure you have the class p4_java.class
#   - run with "./test.sh TEST_CASE_NUM"
#   - e.g. "./test.sh 0"
INPUTDIR=../tests/input
OUTPUTDIR=./my_output
EXPECTEDDIR=../tests/output_expected

if [ ! -d "$OUTPUTDIR" ]; then
  mkdir "$OUTPUTDIR"
  echo "$OUTPUTDIR created."
fi

echo "Test with test$1.my:"
echo "-------------------------------------------------------------"
echo " - Use your compiler to generate x86 translation test$1.s"
echo "-------------------------------------------------------------"
java p4_java <$INPUTDIR/test$1.my >$OUTPUTDIR/test$1.s

echo "-------------------------------------------------------------"
echo " - Verify generated x86 assembles "
echo "   and runs with expected behavior "
echo "-------------------------------------------------------------"
echo "Use gcc to assemble .s your compiler generated ($OUTPUTDIR/test$1.s):"
if gcc -g $OUTPUTDIR/test$1.s -o $OUTPUTDIR/test$1 ; then
  echo " - Gcc assemble passed; Next: run executable generated by gcc"
  echo "-------------------------------------------------------------"
  $OUTPUTDIR/test$1
else
  echo "-- Gcc assemble failed"
fi

echo "-------------------------------------------------------------"
echo "Assemble and run provided .s sample ($EXPECTEDDIR/test$1.s):"
gcc -g -o $OUTPUTDIR/test$1_sample  $EXPECTEDDIR/test$1.s
$OUTPUTDIR/test$1_sample

